## NumPy - Introducción

**NumPy** es una librería utilizada para el manejo de vectores y matrices multidimensionales (conocidos como arrays), cuenta con múltiples funciones para trabajar con estos objetos.

In [1]:
import numpy as np

In [2]:
# Versión de NumPy

print(f"numpy=={np.__version__}")

numpy==2.1.3


#### Arrays

Un array es un objeto multidimensional que puede contener elementos del mismo tipo de datos. Se utiliza para representar datos numéricos, como **vectores**, **matrices** o **tensores**.

- Llamaremos **vectores** a los arrays **uni-dimensionales**.
- Llamaremos **matrices** a los arrays **bi-dimensionales**.
- Llamaremos **tensores** a los arrays **tri-dimensionales** o de más dimensiones.

In [3]:
lista = [1, 2, 3]

type(lista)

list

In [4]:
# Usando la función np.array() podemos castear una lista a un objeto numpy.ndarray

array = np.array(lista)

array

array([1, 2, 3])

In [5]:
# numpy.ndarray se puede traducir como: "n-dimension array"

type(array)

numpy.ndarray

In [6]:
# Si tenemos una lista de listas, NumPy lo transformará como una matriz

mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

mat = np.array(mat)

mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# np.linspace(a, b, n) - linEAR space
# Genera un array de n elementos, que van desde a hasta b.
# Todos los números están espaciados uniformemente.

np.linspace(start = 0, stop = 1, num = 10)

# Esta función la usaremos más adelante

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

**Métodos para arrays**:

|Métodos      |Descripción                                   |
|-------------|----------------------------------------------|
|**.min()**   |Retorna el mínimo de un array.                |
|**.max()**   |Retorna el máximo de un array.                |
|**.argmax()**|Retorna el índice del mayor valor de un array.|
|**.argmin()**|Retorna el índice del menor valor de un array.|
|**.sum()**   |Retorna la suma de los elementos de un array. |
|**.sort()**  |Ordena de menor a mayor el array.             |

In [6]:
# Creamos un np.array para probar los métodos

array = np.array([46, -46, 61, -72, 40, 39, -94, 46, -23, -95, -25, 83, 29, 81, -50, 79, 6, 29, 99, 53])

array

array([ 46, -46,  61, -72,  40,  39, -94,  46, -23, -95, -25,  83,  29,
        81, -50,  79,   6,  29,  99,  53])

In [8]:
# .min()
# Funciona igual que la función min()

array.min()

np.int64(-95)

In [9]:
# .max()
# Funciona igual que la función max()

array.max()

np.int64(99)

In [10]:
# .argmax()
# Retorna el índice del mayor valor del array

array.argmax()

np.int64(18)

In [11]:
# .argmin()
# Retorna el índice del menor valor del array

array.argmin()

np.int64(9)

In [16]:
# .sum()
# Funciona igual que la función sum()

# con numpy
array.sum()

# sin numpy
suma = 0
for numero in array:
    suma += numero
    
print(suma)
print(array.sum())

286
286


In [17]:
# .sort()
# Funciona igual que el método sort() de las listas
# Es un método in-place y no retorna nada

print(f"Array antes de ordenarlo: {array}")

array.sort()

print(f"Array después de ordenarlo: {array}")

Array antes de ordenarlo: [ 46 -46  61 -72  40  39 -94  46 -23 -95 -25  83  29  81 -50  79   6  29
  99  53]
Array después de ordenarlo: [-95 -94 -72 -50 -46 -25 -23   6  29  29  39  40  46  46  53  61  79  81
  83  99]


### Funciones Matemáticas

**NumPy** cuenta con una gran variedad de funciones matemáticas, estas funciones pueden recibir como parámetro de entrada:
- Números: _**int**_, _**float**_.
- **Listas** o **Arrays**.

|Funciones      |Descripción                                            |
|---------------|-------------------------------------------------------|
|**np.max()**   |Retorna el máximo de un array.                         |
|**np.min()**   |Retorna el mínimo de un array.                         |
|**np.sum()**   |Retorna la suma de los elementos de un array.          |
|**np.abs()**   |Retorna el valor absoluto de los elementos de un array.|
|**np.round()** |Función para redondear.                                |
|**np.power()** |Función para aplicar potencia.                         |
|**np.sqrt()**  |Raíz cuadrada.                                         |
|**np.log2()**  |Función logarítimo base 2.                             |
|**np.log10()** |Función logarítimo base 10.                            |
|**np.log()**   |Función logarítmo natural o base e.                    |
|**np.sin()**   |Función seno.                                          |
|**np.cos()**   |Función coseno.                                        |
|**np.tan()**   |Función tangete.                                       |
|**np.arcsin()**|Función arcoseno.                                      |
|**np.arccos()**|Función arcocoseno.                                    |
|**np.arctan()**|Función arcotangente.                                  |

Si el parámetro de entrada es una **lista** o **array**, la función transformará todo los elementos y retornará un **array**.

In [18]:
# Probando con un número

x = 100.1234

print(f"log: {np.log(x)}")
print(f"sqrt: {np.sqrt(x)}")
print(f"round: {np.round(x, 2)}")

log: 4.6064034252358725
sqrt: 10.006168097728521
round: 100.12


In [16]:
# Array para hacer pruebas

array = np.array([43.414, 9.65, 22.286, 11.478, 98.206, 16.849, 24.423, 6.106, 79.175, 50.977,
                  6.167, 61.731, 16.469, 24.245, 51.944, 98.764, 96.294, 20.621, 30.935, 72.7])

array

array([43.414,  9.65 , 22.286, 11.478, 98.206, 16.849, 24.423,  6.106,
       79.175, 50.977,  6.167, 61.731, 16.469, 24.245, 51.944, 98.764,
       96.294, 20.621, 30.935, 72.7  ])

In [19]:
# np.max() retorna el máximo de un array
# Se puede usar como función o como método

np.max(array)

np.int64(99)

In [21]:
# np.min() retorna el mínimo de un array
# Se puede usar como función o como método
print(np.min(array))

-95


In [19]:
# np.round() redondea todos los números de un array

np.round(array, 2)

array([43.41,  9.65, 22.29, 11.48, 98.21, 16.85, 24.42,  6.11, 79.18,
       50.98,  6.17, 61.73, 16.47, 24.24, 51.94, 98.76, 96.29, 20.62,
       30.94, 72.7 ])

In [20]:
# np.sqrt() aplica raíz cuadrada a los números de un array

np.sqrt(array)

array([6.58893011, 3.10644491, 4.72080502, 3.38791972, 9.90989405,
       4.10475334, 4.94196317, 2.47103217, 8.89803349, 7.13981792,
       2.48334452, 7.85690779, 4.05820157, 4.9239212 , 7.2072186 ,
       9.93800785, 9.81295063, 4.54103512, 5.56192413, 8.5264295 ])

In [21]:
# np.log() aplica logarítmo natural a los números de un array

np.log(array)

array([3.77078197, 2.26695792, 3.10395868, 2.44043216, 4.58706731,
       2.82429131, 3.19552531, 1.80927189, 4.37166059, 3.93137455,
       1.8192125 , 4.12278624, 2.80147983, 3.18821041, 3.95016622,
       4.59273317, 4.56740601, 3.02630997, 3.43188823, 4.28634138])

In [22]:
# np.sin() aplica la función seno a los números de un array

np.sin(array)

array([-0.53819764, -0.2233228 , -0.29059769, -0.88587217, -0.72884105,
       -0.90906594, -0.65163751, -0.17625965, -0.59332536,  0.65298387,
       -0.11592409, -0.89159399, -0.68967254, -0.77564807,  0.99420368,
       -0.98082057,  0.8890987 ,  0.97993768, -0.46260081, -0.42898512])

In [23]:
# np.cos() aplica la función coseno a los números de un array

np.cos(array)

array([ 0.84281867, -0.97474454, -0.95684533,  0.46392941, -0.68468294,
       -0.41665227,  0.75853053,  0.98434371, -0.80496274,  0.75737182,
        0.99325808,  0.45283569, -0.72412139,  0.63116565, -0.10751301,
       -0.19491284, -0.45771552, -0.19930413,  0.88656669, -0.90331156])

In [24]:
# np.abs() aplica la función valor absoluto a los números de un array
# Todos los números pasan a ser positivos

np.abs(np.cos(array))

array([0.84281867, 0.97474454, 0.95684533, 0.46392941, 0.68468294,
       0.41665227, 0.75853053, 0.98434371, 0.80496274, 0.75737182,
       0.99325808, 0.45283569, 0.72412139, 0.63116565, 0.10751301,
       0.19491284, 0.45771552, 0.19930413, 0.88656669, 0.90331156])

In [25]:
# np.power() recibe 2 elementos, un array y una potencia
# Eleva todos los elementos del array a esa potencia

np.power(array, 2)

array([1884.775396,   93.1225  ,  496.665796,  131.744484, 9644.418436,
        283.888801,  596.482929,   37.283236, 6268.680625, 2598.654529,
         38.031889, 3810.716361,  271.227961,  587.820025, 2698.179136,
       9754.327696, 9272.534436,  425.225641,  956.974225, 5285.29    ])

In [26]:
# Si usamos 1/2 es como si aplicaramos raíz cuadrada

np.power(array, 1/2)

array([6.58893011, 3.10644491, 4.72080502, 3.38791972, 9.90989405,
       4.10475334, 4.94196317, 2.47103217, 8.89803349, 7.13981792,
       2.48334452, 7.85690779, 4.05820157, 4.9239212 , 7.2072186 ,
       9.93800785, 9.81295063, 4.54103512, 5.56192413, 8.5264295 ])

### Not a Number (NaN)

**NaN** es un término que se utiliza para referirse a elementos que no tienen definición matemática. En **NumPy** este valor se utiliza para indicar que un elemento en un array no representa un número valido.

- Se utiliza para llenar espacios vacíos o datos faltantes en arrays.

- Cualquier operación matemática que incluya un **NaN** dará siempre como resultado un **NaN**.

- Existe en **NumPy** y cualquier otra librería relacionada, como **pandas**, **sklearn** o **tensorflow**.

In [27]:
# NaN

np.nan

nan

In [22]:
# Operaciones matemáticas con NaN siempre retorna NaN

np.nan**2

nan

In [23]:
# Generamos un array de NaN's

array_nan = np.array([np.nan, np.nan, np.nan, np.nan])

array_nan

array([nan, nan, nan, nan])

In [24]:
# np.sum() al array de NaN's da como resultado NaN

np.sum(array_nan)

np.float64(nan)

In [25]:
# Existe en NumPy una función para verificar si una variable/objeto es un NaN
# np.isnan()

# Probamos con un número
np.isnan(1)

np.False_

In [32]:
# Probamos con un NaN

np.isnan(np.nan)

True

In [33]:
# No se pueden comparar NaN's 

np.nan == np.nan

# Rarísimo

False

In [34]:
##############################################################################################################################